// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package srcgql

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/Khan/genqlient/graphql"
)

// A specific kind of external service.
type ExternalServiceKind string

const (
	ExternalServiceKindAwscodecommit   ExternalServiceKind = "AWSCODECOMMIT"
	ExternalServiceKindAzuredevops     ExternalServiceKind = "AZUREDEVOPS"
	ExternalServiceKindBitbucketcloud  ExternalServiceKind = "BITBUCKETCLOUD"
	ExternalServiceKindBitbucketserver ExternalServiceKind = "BITBUCKETSERVER"
	ExternalServiceKindGerrit          ExternalServiceKind = "GERRIT"
	ExternalServiceKindGithub          ExternalServiceKind = "GITHUB"
	ExternalServiceKindGitlab          ExternalServiceKind = "GITLAB"
	ExternalServiceKindGitolite        ExternalServiceKind = "GITOLITE"
	ExternalServiceKindGomodules       ExternalServiceKind = "GOMODULES"
	ExternalServiceKindJvmpackages     ExternalServiceKind = "JVMPACKAGES"
	ExternalServiceKindNpmpackages     ExternalServiceKind = "NPMPACKAGES"
	ExternalServiceKindOther           ExternalServiceKind = "OTHER"
	ExternalServiceKindPagure          ExternalServiceKind = "PAGURE"
	ExternalServiceKindPerforce        ExternalServiceKind = "PERFORCE"
	ExternalServiceKindPhabricator     ExternalServiceKind = "PHABRICATOR"
	ExternalServiceKindPythonpackages  ExternalServiceKind = "PYTHONPACKAGES"
	ExternalServiceKindRustpackages    ExternalServiceKind = "RUSTPACKAGES"
	ExternalServiceKindRubypackages    ExternalServiceKind = "RUBYPACKAGES"
)

// GetExternalServicesExternalServicesExternalServiceConnection includes the requested fields of the GraphQL type ExternalServiceConnection.
// The GraphQL type's documentation follows.
//
// A list of external services.
type GetExternalServicesExternalServicesExternalServiceConnection struct {
	// A list of external services.
	Nodes []GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalService `json:"nodes"`
}

// GetNodes returns GetExternalServicesExternalServicesExternalServiceConnection.Nodes, and is useful for accessing the field via an interface.
func (v *GetExternalServicesExternalServicesExternalServiceConnection) GetNodes() []GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalService {
	return v.Nodes
}

// GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalService includes the requested fields of the GraphQL type ExternalService.
// The GraphQL type's documentation follows.
//
// A configured external service.
type GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalService struct {
	// The kind of external service.
	Kind ExternalServiceKind `json:"kind"`
	// The external service's unique ID.
	Id string `json:"id"`
	// The display name of the external service.
	DisplayName string `json:"displayName"`
	// The JSON configuration of the external service.
	Config string `json:"config"`
	// When the external service was created.
	CreatedAt time.Time `json:"createdAt"`
	// When the external service was last updated.
	UpdatedAt time.Time `json:"updatedAt"`
	// The number of repos synced by the external service.
	RepoCount int `json:"repoCount"`
	// LastSyncAt is the time the last sync job was run for this code host. Null if it
	// has never been synced so far.
	LastSyncAt *time.Time `json:"lastSyncAt"`
	// External services are synced with code hosts in the background. This optional field
	// will contain any errors that occurred during the most recent completed sync.
	LastSyncError *string `json:"lastSyncError"`
	// The timestamp of the next sync job. Null if not scheduled for a re-sync.
	NextSyncAt *time.Time `json:"nextSyncAt"`
	// Checks the availability of the external service.
	CheckConnection GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceAvailability `json:"-"`
}

// GetKind returns GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalService.Kind, and is useful for accessing the field via an interface.
func (v *GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalService) GetKind() ExternalServiceKind {
	return v.Kind
}

// GetId returns GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalService.Id, and is useful for accessing the field via an interface.
func (v *GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalService) GetId() string {
	return v.Id
}

// GetDisplayName returns GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalService.DisplayName, and is useful for accessing the field via an interface.
func (v *GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalService) GetDisplayName() string {
	return v.DisplayName
}

// GetConfig returns GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalService.Config, and is useful for accessing the field via an interface.
func (v *GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalService) GetConfig() string {
	return v.Config
}

// GetCreatedAt returns GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalService.CreatedAt, and is useful for accessing the field via an interface.
func (v *GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalService) GetCreatedAt() time.Time {
	return v.CreatedAt
}

// GetUpdatedAt returns GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalService.UpdatedAt, and is useful for accessing the field via an interface.
func (v *GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalService) GetUpdatedAt() time.Time {
	return v.UpdatedAt
}

// GetRepoCount returns GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalService.RepoCount, and is useful for accessing the field via an interface.
func (v *GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalService) GetRepoCount() int {
	return v.RepoCount
}

// GetLastSyncAt returns GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalService.LastSyncAt, and is useful for accessing the field via an interface.
func (v *GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalService) GetLastSyncAt() *time.Time {
	return v.LastSyncAt
}

// GetLastSyncError returns GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalService.LastSyncError, and is useful for accessing the field via an interface.
func (v *GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalService) GetLastSyncError() *string {
	return v.LastSyncError
}

// GetNextSyncAt returns GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalService.NextSyncAt, and is useful for accessing the field via an interface.
func (v *GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalService) GetNextSyncAt() *time.Time {
	return v.NextSyncAt
}

// GetCheckConnection returns GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalService.CheckConnection, and is useful for accessing the field via an interface.
func (v *GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalService) GetCheckConnection() GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceAvailability {
	return v.CheckConnection
}

func (v *GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalService) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalService
		CheckConnection json.RawMessage `json:"checkConnection"`
		graphql.NoUnmarshalJSON
	}
	firstPass.GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalService = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.CheckConnection
		src := firstPass.CheckConnection
		if len(src) != 0 && string(src) != "null" {
			err = __unmarshalGetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceAvailability(
				src, dst)
			if err != nil {
				return fmt.Errorf(
					"unable to unmarshal GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalService.CheckConnection: %w", err)
			}
		}
	}
	return nil
}

type __premarshalGetExternalServicesExternalServicesExternalServiceConnectionNodesExternalService struct {
	Kind ExternalServiceKind `json:"kind"`

	Id string `json:"id"`

	DisplayName string `json:"displayName"`

	Config string `json:"config"`

	CreatedAt time.Time `json:"createdAt"`

	UpdatedAt time.Time `json:"updatedAt"`

	RepoCount int `json:"repoCount"`

	LastSyncAt *time.Time `json:"lastSyncAt"`

	LastSyncError *string `json:"lastSyncError"`

	NextSyncAt *time.Time `json:"nextSyncAt"`

	CheckConnection json.RawMessage `json:"checkConnection"`
}

func (v *GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalService) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalService) __premarshalJSON() (*__premarshalGetExternalServicesExternalServicesExternalServiceConnectionNodesExternalService, error) {
	var retval __premarshalGetExternalServicesExternalServicesExternalServiceConnectionNodesExternalService

	retval.Kind = v.Kind
	retval.Id = v.Id
	retval.DisplayName = v.DisplayName
	retval.Config = v.Config
	retval.CreatedAt = v.CreatedAt
	retval.UpdatedAt = v.UpdatedAt
	retval.RepoCount = v.RepoCount
	retval.LastSyncAt = v.LastSyncAt
	retval.LastSyncError = v.LastSyncError
	retval.NextSyncAt = v.NextSyncAt
	{

		dst := &retval.CheckConnection
		src := v.CheckConnection
		var err error
		*dst, err = __marshalGetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceAvailability(
			&src)
		if err != nil {
			return nil, fmt.Errorf(
				"unable to marshal GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalService.CheckConnection: %w", err)
		}
	}
	return &retval, nil
}

// GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceAvailability includes the requested fields of the GraphQL interface ExternalServiceAvailability.
//
// GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceAvailability is implemented by the following types:
// GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceAvailabilityUnknown
// GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceAvailable
// GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceUnavailable
// The GraphQL type's documentation follows.
//
// Availability status of an external service for diagnostic purposes.
//
// This is so that the UI can surface whether the external service
// can serve requests, and if not, why is the reason for that.
type GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceAvailability interface {
	implementsGraphQLInterfaceGetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceAvailability()
	// GetTypename returns the receiver's concrete GraphQL type-name (see interface doc for possible values).
	GetTypename() *string
}

func (v *GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceAvailabilityUnknown) implementsGraphQLInterfaceGetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceAvailability() {
}
func (v *GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceAvailable) implementsGraphQLInterfaceGetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceAvailability() {
}
func (v *GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceUnavailable) implementsGraphQLInterfaceGetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceAvailability() {
}

func __unmarshalGetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceAvailability(b []byte, v *GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceAvailability) error {
	if string(b) == "null" {
		return nil
	}

	var tn struct {
		TypeName string `json:"__typename"`
	}
	err := json.Unmarshal(b, &tn)
	if err != nil {
		return err
	}

	switch tn.TypeName {
	case "ExternalServiceAvailabilityUnknown":
		*v = new(GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceAvailabilityUnknown)
		return json.Unmarshal(b, *v)
	case "ExternalServiceAvailable":
		*v = new(GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceAvailable)
		return json.Unmarshal(b, *v)
	case "ExternalServiceUnavailable":
		*v = new(GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceUnavailable)
		return json.Unmarshal(b, *v)
	case "":
		return fmt.Errorf(
			"response was missing ExternalServiceAvailability.__typename")
	default:
		return fmt.Errorf(
			`unexpected concrete type for GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceAvailability: "%v"`, tn.TypeName)
	}
}

func __marshalGetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceAvailability(v *GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceAvailability) ([]byte, error) {

	var typename string
	switch v := (*v).(type) {
	case *GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceAvailabilityUnknown:
		typename = "ExternalServiceAvailabilityUnknown"

		result := struct {
			TypeName string `json:"__typename"`
			*GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceAvailabilityUnknown
		}{typename, v}
		return json.Marshal(result)
	case *GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceAvailable:
		typename = "ExternalServiceAvailable"

		result := struct {
			TypeName string `json:"__typename"`
			*GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceAvailable
		}{typename, v}
		return json.Marshal(result)
	case *GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceUnavailable:
		typename = "ExternalServiceUnavailable"

		result := struct {
			TypeName string `json:"__typename"`
			*GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceUnavailable
		}{typename, v}
		return json.Marshal(result)
	case nil:
		return []byte("null"), nil
	default:
		return nil, fmt.Errorf(
			`unexpected concrete type for GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceAvailability: "%T"`, v)
	}
}

// GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceAvailabilityUnknown includes the requested fields of the GraphQL type ExternalServiceAvailabilityUnknown.
// The GraphQL type's documentation follows.
//
// Availability for some external services may not be determined, or only partially
// supported. In that case unknown variant of ExternalServiceAvailability is returned.
type GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceAvailabilityUnknown struct {
	Typename *string `json:"__typename"`
	// User-friendly textual description of the implementation status of availability.
	// This is expected to be tied to specific kinds of external services.
	ImplementationNote string `json:"implementationNote"`
}

// GetTypename returns GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceAvailabilityUnknown.Typename, and is useful for accessing the field via an interface.
func (v *GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceAvailabilityUnknown) GetTypename() *string {
	return v.Typename
}

// GetImplementationNote returns GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceAvailabilityUnknown.ImplementationNote, and is useful for accessing the field via an interface.
func (v *GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceAvailabilityUnknown) GetImplementationNote() string {
	return v.ImplementationNote
}

// GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceAvailable includes the requested fields of the GraphQL type ExternalServiceAvailable.
// The GraphQL type's documentation follows.
//
// Indicator that the external service was recently found to be available.
type GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceAvailable struct {
	Typename *string `json:"__typename"`
	// The timestamp of the last successful availability check that was performed.
	LastCheckedAt time.Time `json:"lastCheckedAt"`
}

// GetTypename returns GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceAvailable.Typename, and is useful for accessing the field via an interface.
func (v *GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceAvailable) GetTypename() *string {
	return v.Typename
}

// GetLastCheckedAt returns GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceAvailable.LastCheckedAt, and is useful for accessing the field via an interface.
func (v *GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceAvailable) GetLastCheckedAt() time.Time {
	return v.LastCheckedAt
}

// GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceUnavailable includes the requested fields of the GraphQL type ExternalServiceUnavailable.
// The GraphQL type's documentation follows.
//
// Indicator that the external service was recently not found available.
type GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceUnavailable struct {
	Typename *string `json:"__typename"`
	// User-friendly textual description of supposed reason why the service is not available.
	SuspectedReason string `json:"suspectedReason"`
}

// GetTypename returns GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceUnavailable.Typename, and is useful for accessing the field via an interface.
func (v *GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceUnavailable) GetTypename() *string {
	return v.Typename
}

// GetSuspectedReason returns GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceUnavailable.SuspectedReason, and is useful for accessing the field via an interface.
func (v *GetExternalServicesExternalServicesExternalServiceConnectionNodesExternalServiceCheckConnectionExternalServiceUnavailable) GetSuspectedReason() string {
	return v.SuspectedReason
}

// GetExternalServicesResponse is returned by GetExternalServices on success.
type GetExternalServicesResponse struct {
	// Lists external services under given namespace.
	// If no namespace is given, it returns all external services.
	ExternalServices GetExternalServicesExternalServicesExternalServiceConnection `json:"externalServices"`
}

// GetExternalServices returns GetExternalServicesResponse.ExternalServices, and is useful for accessing the field via an interface.
func (v *GetExternalServicesResponse) GetExternalServices() GetExternalServicesExternalServicesExternalServiceConnection {
	return v.ExternalServices
}

// UpdateExternalServiceResponse is returned by UpdateExternalService on success.
type UpdateExternalServiceResponse struct {
	// Updates a external service. Only site admins may perform this mutation.
	UpdateExternalService UpdateExternalServiceUpdateExternalService `json:"updateExternalService"`
}

// GetUpdateExternalService returns UpdateExternalServiceResponse.UpdateExternalService, and is useful for accessing the field via an interface.
func (v *UpdateExternalServiceResponse) GetUpdateExternalService() UpdateExternalServiceUpdateExternalService {
	return v.UpdateExternalService
}

// UpdateExternalServiceUpdateExternalService includes the requested fields of the GraphQL type ExternalService.
// The GraphQL type's documentation follows.
//
// A configured external service.
type UpdateExternalServiceUpdateExternalService struct {
	// The kind of external service.
	Kind ExternalServiceKind `json:"kind"`
	// The external service's unique ID.
	Id string `json:"id"`
	// The display name of the external service.
	DisplayName string `json:"displayName"`
	// The JSON configuration of the external service.
	Config string `json:"config"`
	// When the external service was created.
	CreatedAt time.Time `json:"createdAt"`
	// When the external service was last updated.
	UpdatedAt time.Time `json:"updatedAt"`
}

// GetKind returns UpdateExternalServiceUpdateExternalService.Kind, and is useful for accessing the field via an interface.
func (v *UpdateExternalServiceUpdateExternalService) GetKind() ExternalServiceKind { return v.Kind }

// GetId returns UpdateExternalServiceUpdateExternalService.Id, and is useful for accessing the field via an interface.
func (v *UpdateExternalServiceUpdateExternalService) GetId() string { return v.Id }

// GetDisplayName returns UpdateExternalServiceUpdateExternalService.DisplayName, and is useful for accessing the field via an interface.
func (v *UpdateExternalServiceUpdateExternalService) GetDisplayName() string { return v.DisplayName }

// GetConfig returns UpdateExternalServiceUpdateExternalService.Config, and is useful for accessing the field via an interface.
func (v *UpdateExternalServiceUpdateExternalService) GetConfig() string { return v.Config }

// GetCreatedAt returns UpdateExternalServiceUpdateExternalService.CreatedAt, and is useful for accessing the field via an interface.
func (v *UpdateExternalServiceUpdateExternalService) GetCreatedAt() time.Time { return v.CreatedAt }

// GetUpdatedAt returns UpdateExternalServiceUpdateExternalService.UpdatedAt, and is useful for accessing the field via an interface.
func (v *UpdateExternalServiceUpdateExternalService) GetUpdatedAt() time.Time { return v.UpdatedAt }

// __UpdateExternalServiceInput is used internally by genqlient
type __UpdateExternalServiceInput struct {
	Id          string `json:"id"`
	DisplayName string `json:"displayName"`
	Config      string `json:"config"`
}

// GetId returns __UpdateExternalServiceInput.Id, and is useful for accessing the field via an interface.
func (v *__UpdateExternalServiceInput) GetId() string { return v.Id }

// GetDisplayName returns __UpdateExternalServiceInput.DisplayName, and is useful for accessing the field via an interface.
func (v *__UpdateExternalServiceInput) GetDisplayName() string { return v.DisplayName }

// GetConfig returns __UpdateExternalServiceInput.Config, and is useful for accessing the field via an interface.
func (v *__UpdateExternalServiceInput) GetConfig() string { return v.Config }

// The query or mutation executed by GetExternalServices.
const GetExternalServices_Operation = `
query GetExternalServices {
	externalServices {
		nodes {
			kind
			id
			displayName
			config
			createdAt
			updatedAt
			repoCount
			lastSyncAt
			lastSyncError
			nextSyncAt
			checkConnection {
				__typename
				... on ExternalServiceAvailable {
					lastCheckedAt
				}
				... on ExternalServiceUnavailable {
					suspectedReason
				}
				... on ExternalServiceAvailabilityUnknown {
					implementationNote
				}
			}
		}
	}
}
`

// GetExternalServices collects useful summary information for configured
// external services. Note that config automatically redacts secrets.
func GetExternalServices(
	ctx context.Context,
	client graphql.Client,
) (*GetExternalServicesResponse, error) {
	req := &graphql.Request{
		OpName: "GetExternalServices",
		Query:  GetExternalServices_Operation,
	}
	var err error

	var data GetExternalServicesResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by UpdateExternalService.
const UpdateExternalService_Operation = `
mutation UpdateExternalService ($id: ID!, $displayName: String!, $config: String!) {
	updateExternalService(input: {id:$id,displayName:$displayName,config:$config}) {
		kind
		id
		displayName
		config
		createdAt
		updatedAt
	}
}
`

func UpdateExternalService(
	ctx context.Context,
	client graphql.Client,
	id string,
	displayName string,
	config string,
) (*UpdateExternalServiceResponse, error) {
	req := &graphql.Request{
		OpName: "UpdateExternalService",
		Query:  UpdateExternalService_Operation,
		Variables: &__UpdateExternalServiceInput{
			Id:          id,
			DisplayName: displayName,
			Config:      config,
		},
	}
	var err error

	var data UpdateExternalServiceResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}
